const fs = require("fs");
const path = require("path");

const dir = path.join(__dirname, "..", "messages");

// Canton names per language - Swiss official/common names
const cantonsByLocale = {
  en: [
    { value: "AG", label: "Aargau (AG)" },
    { value: "AI", label: "Appenzell Inner Rhodes (AI)" },
    { value: "AR", label: "Appenzell Outer Rhodes (AR)" },
    { value: "BE", label: "Bern (BE)" },
    { value: "BL", label: "Basel-Landschaft (BL)" },
    { value: "BS", label: "Basel-City (BS)" },
    { value: "FR", label: "Fribourg (FR)" },
    { value: "GE", label: "Geneva (GE)" },
    { value: "GL", label: "Glarus (GL)" },
    { value: "GR", label: "Graubünden (GR)" },
    { value: "JU", label: "Jura (JU)" },
    { value: "LU", label: "Lucerne (LU)" },
    { value: "NE", label: "Neuchâtel (NE)" },
    { value: "NW", label: "Nidwalden (NW)" },
    { value: "OW", label: "Obwalden (OW)" },
    { value: "SG", label: "St. Gallen (SG)" },
    { value: "SH", label: "Schaffhausen (SH)" },
    { value: "SO", label: "Solothurn (SO)" },
    { value: "SZ", label: "Schwyz (SZ)" },
    { value: "TG", label: "Thurgau (TG)" },
    { value: "TI", label: "Ticino (TI)" },
    { value: "UR", label: "Uri (UR)" },
    { value: "VD", label: "Vaud (VD)" },
    { value: "VS", label: "Valais (VS)" },
    { value: "ZG", label: "Zug (ZG)" },
    { value: "ZH", label: "Zurich (ZH)" },
  ],
  fr: [
    { value: "AG", label: "Argovie (AG)" },
    { value: "AI", label: "Appenzell Rhodes-Int. (AI)" },
    { value: "AR", label: "Appenzell Rhodes-Ext. (AR)" },
    { value: "BE", label: "Berne (BE)" },
    { value: "BL", label: "Bâle-Campagne (BL)" },
    { value: "BS", label: "Bâle-Ville (BS)" },
    { value: "FR", label: "Fribourg (FR)" },
    { value: "GE", label: "Genève (GE)" },
    { value: "GL", label: "Glaris (GL)" },
    { value: "GR", label: "Grisons (GR)" },
    { value: "JU", label: "Jura (JU)" },
    { value: "LU", label: "Lucerne (LU)" },
    { value: "NE", label: "Neuchâtel (NE)" },
    { value: "NW", label: "Nidwald (NW)" },
    { value: "OW", label: "Obwald (OW)" },
    { value: "SG", label: "St-Gall (SG)" },
    { value: "SH", label: "Schaffhouse (SH)" },
    { value: "SO", label: "Soleure (SO)" },
    { value: "SZ", label: "Schwyz (SZ)" },
    { value: "TG", label: "Thurgovie (TG)" },
    { value: "TI", label: "Tessin (TI)" },
    { value: "UR", label: "Uri (UR)" },
    { value: "VD", label: "Vaud (VD)" },
    { value: "VS", label: "Valais (VS)" },
    { value: "ZG", label: "Zoug (ZG)" },
    { value: "ZH", label: "Zurich (ZH)" },
  ],
  de: [
    { value: "AG", label: "Aargau (AG)" },
    { value: "AI", label: "Appenzell Innerrhoden (AI)" },
    { value: "AR", label: "Appenzell Ausserrhoden (AR)" },
    { value: "BE", label: "Bern (BE)" },
    { value: "BL", label: "Basel-Landschaft (BL)" },
    { value: "BS", label: "Basel-Stadt (BS)" },
    { value: "FR", label: "Freiburg (FR)" },
    { value: "GE", label: "Genf (GE)" },
    { value: "GL", label: "Glarus (GL)" },
    { value: "GR", label: "Graubünden (GR)" },
    { value: "JU", label: "Jura (JU)" },
    { value: "LU", label: "Luzern (LU)" },
    { value: "NE", label: "Neuenburg (NE)" },
    { value: "NW", label: "Nidwalden (NW)" },
    { value: "OW", label: "Obwalden (OW)" },
    { value: "SG", label: "St. Gallen (SG)" },
    { value: "SH", label: "Schaffhausen (SH)" },
    { value: "SO", label: "Solothurn (SO)" },
    { value: "SZ", label: "Schwyz (SZ)" },
    { value: "TG", label: "Thurgau (TG)" },
    { value: "TI", label: "Tessin (TI)" },
    { value: "UR", label: "Uri (UR)" },
    { value: "VD", label: "Waadt (VD)" },
    { value: "VS", label: "Wallis (VS)" },
    { value: "ZG", label: "Zug (ZG)" },
    { value: "ZH", label: "Zürich (ZH)" },
  ],
  it: [
    { value: "AG", label: "Argovia (AG)" },
    { value: "AI", label: "Appenzello Interno (AI)" },
    { value: "AR", label: "Appenzello Esterno (AR)" },
    { value: "BE", label: "Berna (BE)" },
    { value: "BL", label: "Basilea-Campagna (BL)" },
    { value: "BS", label: "Basilea-Città (BS)" },
    { value: "FR", label: "Friburgo (FR)" },
    { value: "GE", label: "Ginevra (GE)" },
    { value: "GL", label: "Glarona (GL)" },
    { value: "GR", label: "Grigioni (GR)" },
    { value: "JU", label: "Giura (JU)" },
    { value: "LU", label: "Lucerna (LU)" },
    { value: "NE", label: "Neuchâtel (NE)" },
    { value: "NW", label: "Nidvaldo (NW)" },
    { value: "OW", label: "Obvaldo (OW)" },
    { value: "SG", label: "San Gallo (SG)" },
    { value: "SH", label: "Sciaffusa (SH)" },
    { value: "SO", label: "Soletta (SO)" },
    { value: "SZ", label: "Svitto (SZ)" },
    { value: "TG", label: "Turgovia (TG)" },
    { value: "TI", label: "Ticino (TI)" },
    { value: "UR", label: "Uri (UR)" },
    { value: "VD", label: "Vaud (VD)" },
    { value: "VS", label: "Vallese (VS)" },
    { value: "ZG", label: "Zugo (ZG)" },
    { value: "ZH", label: "Zurigo (ZH)" },
  ],
};

["en", "fr", "de", "it"].forEach((locale) => {
  const filePath = path.join(dir, `${locale}.json`);
  if (!fs.existsSync(filePath)) return;
  const content = JSON.parse(fs.readFileSync(filePath, "utf-8"));
  // Key path must match: Calculator -> Form -> fields2 -> canton -> options
  // (as used in t.raw("fields2.canton.options") inside Calculator.Form namespace)
  content.Calculator.Form.fields2.canton.options = cantonsByLocale[locale];
  fs.writeFileSync(filePath, JSON.stringify(content, null, 2));
  console.log(`Updated ${locale}.json with canton options`);
});
